AuthSharp/Controllers/UsersAdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using AuthSharp.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;

namespace AuthSharp.Controllers
{

    [Authorize(Roles = "Administrators")]
    public class UsersAdministrationController : Controller
    {
        ApplicationDbContext _dbContext;

        ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? (_userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>());
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationDbContext DbContext
        {
            get
            {
                return _dbContext ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            }
            private set
            {
                _dbContext = value;
            }
        }
        List<ApplicationUser> NormalUsers
        {
            get
            {
                //var roleManager = new ApplicationRoleManager(new RoleStore<IdentityRole>(HttpContext.GetOwinContext().Get<ApplicationDbContext>()));
                var userIds = DbContext.Roles.Single(role => role.Name == "Users").Users.Select(a => a.UserId);
                //roleManager.Roles.Single(role => role.Name == "Administrator").Users.Select(a=>a.UserId);
                return DbContext.Users.Where(user => userIds.Contains(user.Id)).ToList();
            }
        }
        public ApplicationUser CurrentApplicationUser
        {
            get
            {
                return DbContext.Users.Single(user => user.UserName == User.Identity.Name);
            }
        }

        // GET: UsersAdministration
        public ActionResult Index(UsersAdministrationMessageId? message)
        {
            ViewBag.StatusMessage =
                message == UsersAdministrationMessageId.DeleteSuccess ? "成功成功删除用户。"
                : message == UsersAdministrationMessageId.ResetPasswordSuccess ? "成功设置密码。"
                : message == UsersAdministrationMessageId.Error ? "出现错误。"
                : "";
            return View(NormalUsers);
        }

        public ActionResult Details(string id, UsersAdministrationMessageId? message)
        {
            ViewBag.StatusMessage =
                message == UsersAdministrationMessageId.CancelSuccess ? "成功取消请求。。"
                            : message == UsersAdministrationMessageId.ConfirmSuccess ? "成功确认请求，流量已经进入对应账户。"
                            : message == UsersAdministrationMessageId.Error ? "出现错误。"
                            : "";
            var user = GetApplicationUserById(id);
            return View(user);
        }



        private ApplicationUser GetApplicationUserById(string id)
        {
            return DbContext.Users.Single(u => u.Id == id);
        }

        private ApplicationUser GetApplicationUserByName(string username)
        {
            return DbContext.Users.Single(u => u.UserName == username);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult ConfirmedRequest(string uid, Guid rid)
        {
            RemoveRechargeRequestsWith(rid, request =>
            {
                GetApplicationUserById(uid).TrafficRemaining += request.Amount;
            });
            return RedirectToAction("Details", new { id = uid, message = UsersAdministrationMessageId.ConfirmSuccess });
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult CancelRequest(string uid, Guid rid)
        {
            RemoveRechargeRequestsWith(rid, null);
            return RedirectToAction("Details", new { id = uid, message = UsersAdministrationMessageId.CancelSuccess });
        }

        private void RemoveRechargeRequestsWith(Guid id, Action<RechargeRequest> work)
        {
            var request = DbContext.RechargeRequests.Single(r => r.RequestID == id);
            if (work != null) work(request);
            DbContext.RechargeRequests.Remove(request);
            DbContext.SaveChanges();
        }

        public ActionResult SetPassword(string id)
        {
            ResetUserPasswordViewModel model = new ResetUserPasswordViewModel()
            {
                UserName = GetApplicationUserById(id).UserName
            };
            return View(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> SetPassword(ResetUserPasswordViewModel model)
        {
            var user = await UserManager.FindByNameAsync(model.UserName);
            if (user == null)
            {
                ModelState.AddModelError("", "用户不存在。");
                model.NewPassword = model.ConfirmPassword = "";
                return View(model);
            }
            string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
            var result = await UserManager.ResetPasswordAsync(user.Id, code, model.NewPassword);
            return RedirectToAction("Index", new { id = user.Id, message = UsersAdministrationMessageId.ResetPasswordSuccess });
        }

        public async Task<ActionResult> Delete(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                DeleteUserViewModel model = new DeleteUserViewModel() { UserID = user.Id, UserName = user.UserName };
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", new { message = UsersAdministrationMessageId.Error });
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(string userid)
        {
            var user = await UserManager.FindByIdAsync(userid);
            if (user != null)
            {
                await UserManager.DeleteAsync(user);
                return RedirectToAction("Index", new { message = UsersAdministrationMessageId.DeleteSuccess });
            }
            //DbContext.Users.Remove(user);
            //DbContext.SaveChanges();
            return RedirectToAction("Index", new { message = UsersAdministrationMessageId.Error });
        }

        public enum UsersAdministrationMessageId
        {
            DeleteSuccess,
            ResetPasswordSuccess,
            ConfirmSuccess,
            CancelSuccess,
            Error,
        }
    }
}

AuthSharp/Views/UsersAdministration/Delete.cshtml
@model AuthSharp.Models.DeleteUserViewModel

@{
    ViewBag.Title = "删除用户";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Delete", "UsersAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.HiddenFor(m => m.UserID)
    <p>真的要删除 @Model.UserName 吗？</p>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="删除" class="btn btn-danger" />
        </div>
    </div>
}

AuthSharp/Views/UsersAdministration/Details.cshtml
@model AuthSharp.Models.ApplicationUser

@{
    ViewBag.Title = "详细信息";
}

<h2>详细信息</h2>
<p class="text-success">@ViewBag.StatusMessage</p>
<div>
    <h4>@Model.UserName</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.RealName)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.TrafficRemaining)*@
            <p>@Model.RealName</p>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrafficRemaining)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.TrafficRemaining)*@
            <p>@Model.TrafficRemaining</p>
        </dd>

        <dt>
            充值请求 @Model.RechargeRequests.Count 个
        </dt>

        <dd>
            <ul>
                @foreach (var request in Model.RechargeRequests)
                {
                    <li>
                        @Html.Partial("RechargeRequestsDetailsPartial", request)
                        @using (Html.BeginForm("ConfirmedRequest", "UsersAdministration", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @*@Html.Hidden("id", Guid.NewGuid())*@
                            <input type="hidden" id="rid" name="rid" value="@request.RequestID" />
                            <input type="hidden" id="uid" name="uid" value="@Model.Id" />
                            <input type="submit" value="通过" class="btn-link" />
                        }
                        @using (Html.BeginForm("CancelRequest", "UsersAdministration", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @*@Html.Hidden("id", request.RequestID)*@
                            <input type="hidden" id="rid" name="rid" value="@request.RequestID" />
                            <input type="hidden" id="uid" name="uid" value="@Model.Id" />
                            <input type="submit" value="取消" class="btn-link" />
                        }
                    </li>
                }
            </ul>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("回到列表", "Index")
</p>

AuthSharp/Views/UsersAdministration/Index.cshtml
@model IEnumerable<AuthSharp.Models.ApplicationUser>

@{
    ViewBag.Title = "管理";
}

<h2>@ViewBag.Title</h2>

<p class="text-success">@ViewBag.StatusMessage</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrafficRemaining)
        </th>
        <th>
            充值请求
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.TrafficRemaining)*@
                <p>@item.TrafficRemaining</p>
            </td>

            <td>
                @item.RechargeRequests.Count 个
            </td>
            <td>
                @Html.ActionLink("修改密码", "SetPassword", new { id = item.Id }) |
                @Html.ActionLink("详细信息", "Details", new { id = item.Id }) |
                @Html.ActionLink("删除", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

AuthSharp/Views/UsersAdministration/RechargeRequestsDetailsPartial.cshtml
@model AuthSharp.Models.RechargeRequest

<div>
    @*<h4>RechargeRequest</h4>
    <hr />*@
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Amount)*@
            @Model.Amount
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationTime)
        </dd>

    </dl>
</div>

AuthSharp/Views/UsersAdministration/SetPassword.cshtml
@model AuthSharp.Models.ResetUserPasswordViewModel
@{
    ViewBag.Title = "设置用户密码";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("SetPassword", "UsersAdministration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NewPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="设置密码" class="btn btn-default" />
        </div>
    </div>
}